### ISSUE TITLE
Extension for Firefox?

### ISSUE THREAD

**Issue by jakeayy** [ogohogo/is-youtube-channel-monetized-extension#1]
Hi, will there be an extension for firefox someday? Thanks

**Comment by ogohogo** [comment]
It is currently under review. I'll let you know once they approve it!

**Comment by ogohogo** [comment]
Update: now it's live on firefox's add-on store! [https://addons.mozilla.org/en-US/firefox/addon/is-youtube-channel-monetized/](https://addons.mozilla.org/en-US/firefox/addon/is-youtube-channel-monetized/)
