### ISSUE TITLE
I was told to report this

### ISSUE THREAD

**Issue by agoodusernam** [ogohogo/is-youtube-channel-monetized-extension#2]
Failed to gather monetization data for Lethamyr (https://www.youtube.com/@Lethamyr)
![image](https://user-images.githubusercontent.com/90071032/207120172-c34f81ed-aa1f-479c-aade-cde3749adff6.png)

**Comment by ogohogo** [comment]
There's something weird with this channel. Upon refreshing it redirects you to /user/Lethamyr path which throws error 404. I will dig into this futher but it seems to be something with YouTube.

**Comment by 4wincode** [comment]
> There's something weird with this channel. Upon refreshing it redirects you to /user/Lethamyr path which throws error 404. I will dig into this futher but it seems to be something with YouTube.

This is happening to me with other channels as well and is not only preventing the extension from working but also sometimes giving me a 404 like you said.

**Comment by Qr9Vt4Q2DAxv3I0Dh10CBOIHCTvU96KBcpLRLDm** [comment]
nope this is just becuase he is stupid and set a channel redirect as the url he wanted. it's a common thing people do for some reason as they don't seem to be able to read.

**Comment by ogohogo** [comment]
Alright I came to the following conclusion:

There's basically no way to gather monetization data about such channels. Like @Qr9Vt4Q2DAxv3I0Dh10CBOIHCTvU96KBcpLRLDm mentioned, this person has set up custom redirect on their channel. When they introduced handle's update, they've completely screwed the previous username system. While it should also work for `/@test` and `/user/test`, for some users it doesn't work properly. Technically there's a way to get this if you reverse engineer their web API but that's something I - personally can't do. Feel free to submit your changes if you can.
