### ISSUE TITLE
Check if a specific video is monetised

### ISSUE THREAD

**Issue by Qr9Vt4Q2DAxv3I0Dh10CBOIHCTvU96KBcpLRLDm** [ogohogo/is-youtube-channel-monetized-extension#3]
There is also a way to check if a specific video is monetised, can you add that?

**Comment by ogohogo** [comment]
As far as I know there's no way to check that. If you know it, then let me know.

**Comment by Qr9Vt4Q2DAxv3I0Dh10CBOIHCTvU96KBcpLRLDm** [comment]
You can use yt_ad

**Comment by ogohogo** [comment]
Thanks, I'll add it whenever I can.

**Comment by ogohogo** [comment]
I've just noticed it's not really consitant. For example, it shows me yt_ad value when channel is not monetized at all. Is there any other way to check it?

**Comment by Qr9Vt4Q2DAxv3I0Dh10CBOIHCTvU96KBcpLRLDm** [comment]
It just shows if a video is monetised, so it would show if it got a
copyright claim etc.

**Comment by Qr9Vt4Q2DAxv3I0Dh10CBOIHCTvU96KBcpLRLDm** [comment]
Hey there, I see @ShazGuicci using this on twitter, is there any plans to implement this? @ogohogo

**Comment by ogohogo** [comment]
Added in v0.4.0. Goes live once Google approves the release.

**Comment by Qr9Vt4Q2DAxv3I0Dh10CBOIHCTvU96KBcpLRLDm** [comment]
Alright, when will it be on GitHub?

**Comment by Qr9Vt4Q2DAxv3I0Dh10CBOIHCTvU96KBcpLRLDm** [comment]
It already is* I am dumb

**Comment by JonDotExe** [comment]
Nice update. I noticed today that a creator with 2M subs did a video about his favorite movies and it worked perfectly to show that just that video was not monetized.
