### ISSUE TITLE
The Skeppy channel says: "Failed to gather monetization data! Please report this."

### ISSUE THREAD

**Issue by driff2011** [ogohogo/is-youtube-channel-monetized-extension#4]

**Comment by Qr9Vt4Q2DAxv3I0Dh10CBOIHCTvU96KBcpLRLDm** [comment]
Skeppy is stupid, and put his channel redirect to user/Skeppy which is a 404. This can't be fixed.

**Comment by ogohogo** [comment]
Like @Qr9Vt4Q2DAxv3I0Dh10CBOIHCTvU96KBcpLRLDm said, this can't be fixed. This also applies to all channels that has this redirect.
