### ISSUE TITLE
Video is monetised doesn't update until page is refreshed.

### ISSUE THREAD

**Issue by Qr9Vt4Q2DAxv3I0Dh10CBOIHCTvU96KBcpLRLDm** [ogohogo/is-youtube-channel-monetized-extension#5]
When you navigate to a video, it doesn't update until you refresh the page.

**Comment by ogohogo** [comment]
I aim to fix this in v0.4.1. Hopefully i'll get it done by the end of this week.

**Comment by Qr9Vt4Q2DAxv3I0Dh10CBOIHCTvU96KBcpLRLDm** [comment]
Alright sounds good, did you submit the updated extension to firefox btw?

**Comment by ogohogo** [comment]
Yep, for some reason it's still "under review"

**Comment by Qr9Vt4Q2DAxv3I0Dh10CBOIHCTvU96KBcpLRLDm** [comment]
> Yep, for some reason it's still "under review"

Ah, that sucks.. Normally firefox is quick

**Comment by ogohogo** [comment]
Fixed in v0.4.1.
