### ISSUE TITLE
Failed to gather information

### ISSUE THREAD

**Issue by Shromby** [ogohogo/is-youtube-channel-monetized-extension#7]
![Screenshot 2023-07-27 092009](https://github.com/ogohogo/is-youtube-channel-monetized-extension/assets/140676208/e53f5dd6-1bd8-4e45-9db9-36efeea10889)
 i was scrollling on my frend's son youtube channel the i came across the red word says: Failed to gather monetization data! Please report this. pls fix

**Comment by ogohogo** [comment]
Can you give me the URL of this channel?
