### ISSUE TITLE
Extension suddenly stopped working

### ISSUE THREAD

**Issue by JoseErnestoOnGithub** [ogohogo/is-youtube-channel-monetized-extension#9]
### Problem information
Today (November 18, 2023), the extension stopped working. I ran into the following problem that says in this picture:
![Screenshot 2023-11-18 072940](https://github.com/ogohogo/is-youtube-channel-monetized-extension/assets/115112109/88d842c6-18d8-4f11-a493-1a4429a609c7)

Yesterday, the extension was working fine, but today, it ran into this seen in the picture above.

Also, an error is shown on the console that says (no picture, text only):
```
[Is YouTube Channel Monetized?] An error occured while attempting to fetch data from YouTube
TypeError: Cannot read properties of undefined (reading 'split')
```

This error happened on main.js on line number 59.

The main.js will need to be patched to get the extension fully working.

### Channel URL
https://www.youtube.com/@AckyNation

### What will happen?
* Each day until this date, the extension is working fine.
* As of today, it stopped working.

**Comment by ogohogo** [comment]
It looks like YouTube has removed ability to check whenever channel is monetized or not (is_monetization_enabled property appears to be gone). I'll see if there's any other way to retrieve this data.

**Comment by ogohogo** [comment]
There's no way of retrieving that information anymore. Because of that, this repo goes into archived state.
